name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping App 1
        run: curl -fsSL https://rootlytic-dashboard-api.onrender.com

      - name: Ping App 2
        run: curl -fsSL https://rootlytic-observability-2.onrender.com

      - name: Ping App 3
        run: curl -fsSL https://rootlytic-observability-1.onrender.com
